services:
  - type: web
    name: al-saif-gallery
    env: static
    buildCommand: |
      git clone https://github.com/flutter/flutter.git -b stable --depth 1 /opt/flutter
      export PATH="$PATH:/opt/flutter/bin"
      flutter pub get
      flutter build web --web-renderer html --release
    staticPublishPath: build/web
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
